server:
  minSearchLength: 3
  disableUpdateCheck: false
  disablePreviews: false
  disablePreviewResize: false
  disableTypeDetectionByHeader: false
  port: 8080
  baseURL: "/"
  externalUrl: ""
  internalUrl: "http://127.0.0.1:8080"
  logging:
    - output: "stdout"
      noColors: false
  cacheDir: "tmp"
  maxArchiveSize: 50
  filesystem:
    createFilePermission: "660"
    createDirectoryPermission: "770"

  sources:
    - path: "/mnt/personal"
      name: "Personal"
      config:
        denyByDefault: false
        private: false
        disabled: false
        defaultUserScope: "/"
        defaultEnabled: true
        createUserDir: false
    - path: "/mnt/photos"
      name: "Photos"
      config:
        denyByDefault: false
        private: false
        disabled: false
        defaultUserScope: "/"
        defaultEnabled: true
        createUserDir: false
    - path: "/mnt/media"
      name: "Media"
      config:
        denyByDefault: false
        private: false
        disabled: false
        defaultUserScope: "/"
        defaultEnabled: true
        createUserDir: false
    - path: "/mnt/apple"
      name: "Apple"
      config:
        denyByDefault: false
        private: false
        disabled: false
        defaultUserScope: "/"
        defaultEnabled: true
        createUserDir: false
        rules:
          - neverWatchPath: "/"
          - folderPath: "/"
            viewable: true
        # Will be deprecated, no viable alternative as of 03/11/26
        disableIndexing: true

auth:
  tokenExpirationHours: 120
  adminUsername: "root"
  adminPassword: "" # Set via FILEBROWSER_ADMIN_PASSWORD
  methods:
    password:
      enabled: true
      minLength: 5
      signup: false
    oidc:
      enabled: true
      clientId: '' # Set via FILEBROWSER_OIDC_CLIENT_ID
      clientSecret: '' # Set via FILEBROWSER_OIDC_CLIENT_SECRET
      issuerUrl: 'https://auth.${DOMAIN_PUBLIC}'
      scopes: 'email openid profile groups'
      userIdentifier: 'preferred_username'
      disableVerifyTLS: false
      logoutRedirectUrl: ''
      createUser: true
      adminGroup: 'app_admin'
      groupsClaim: 'groups'

frontend:
  name: "NAS - SATA ZFS Pool"
  disableNavButtons: false
  disableDefaultLinks: true
  disableUsedPercentage: false
  description: ""
  styling:
    customCSS: ""
    lightBackground: "#858585"
    darkBackground: "#000000"
    customThemes:
      default:
        description: "The default theme"
        css: ""
      alternative:
        description: "Reduce rounded corners"
        css: "reduce-rounded-corners.css"

userDefaults:
  darkMode: true
  disableSettings: false
  showSelectMultiple: true
  singleClick: true
  showHidden: true
  themeColor: "#363636"
  quickDownload: true
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
