# Swarm secrets for gateway-external stack
# Included via docker compose include directive

secrets:
  cloudflare_dns_api_token_external:
    name: cloudflare_dns_api_token_external_${DEPLOY_VERSION}
    external: true
