secrets:
  global_cloudflare_acme_private_token:
    name: global_cloudflare_acme_private_token_${DEPLOY_VERSION}
    external: true

configs:
  gateway_internal_traefik_dynamic_base:
    name: gateway_internal_traefik_dynamic_base_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/base.yml
  gateway_internal_traefik_dynamic_hass_private:
    name: gateway_internal_traefik_dynamic_hass_private_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/hass-private.yml
