secrets:
  global_db_provisioner_password:
    name: global_db_provisioner_password_${DEPLOY_VERSION}
    external: true
  postgres_superuser_password:
    name: postgres_superuser_password_${DEPLOY_VERSION}
    external: true

configs:
  postgres_init:
    name: postgres_init_${DEPLOY_VERSION}
    file: ./config/postgres/init.sh
