POSTGRES_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:HAIXmORKhOushlnett7UUUI0m2/a5okSZPbjVOfSZ7O9x8X1YzuASLuZJVDfKt6kWkAHPB8fyv289SWvkRS2ig==,iv:a/krn1ow7DWZaTbjaMmhDf2RA8imb4Qn2iblwabGYzs=,tag:Ng7IyByZ3KS3ZiZd70UFpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN2JZc000akRZT0ZKems5
        ckY5czd4dlQ5R2NodkpDdDk1b29ybE5KTmpZCnJRbEVNOHhaVU0wanZJaHIzelZO
        Nk9sKzJiVkxSV1QxMXJCeU9QQ2E1Z1UKLS0tIFZVNlltcDNzdG5HbVdMN1FTVkp2
        RU0wS2ZLcUxGb1ZvbWc1VUgyazNqT28KP6TtRQjnE2RywEcso/QqkfjK4PTvAAdu
        3Ns477xSfIiurFtQFOWSPhkFVzeskOrRdPfT0iU/h3v1jRus5uQsDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T19:18:04Z"
  mac: ENC[AES256_GCM,data:9/5a1taiSpEpHMFS9+uQFEsjEsP/W4kA9E+4TMlaYrX07s/d6dl2brmlKWIi12p7olykehNVMqIAJdaZVuVDzlqOXWs83Yi1uC/SoikWv9qYmW8DRmOxPuZgAFnGsqV+7pKJMYPHm0uV3h94JH68A80IvFBXyQsIFPcLLET6urs=,iv:ZzzG5DQiOy/121hEIr9LVZGgBVDdSkyUGZV2kPjk30M=,tag:g9tIkeRXT+NqBRpcG9iYdw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
