POSTGRES_PASSWORD: ENC[AES256_GCM,data:/tDyqkaJtS68EhlVqQZoeuEWOiwpzuUXrde0z5H5BxwVrt7EhYs/KP3kIf87b4CklW8dRlpQeFYO1a2oiEeNsQ==,iv:ErDrTNCh2RjSIemFRcqlS3CKKbtY28NTkF7uWPBSrWo=,tag:/kyNIYQG72gL3/yCOVAPqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVldOSVMxZCtRbEoramZx
        YXBjZW1JRXJEWXNoTTQ5ejZBRXlBamNhTXhNCjdkRlJzMDQ3ZWJGOHhTVFBQQTFD
        SmdFZzhWV2FzbGhtOG5hTnB0eFdCbUkKLS0tIEZzaWlkUEdqQXo2REFUN2hpcVJQ
        QW9PV1F5SE8rNks4L1lyOVU5UlhOVW8Kw7l6JSPS0X9r3pUSgNHF5HnlUW/BSjrr
        V/HFwbr3I0fo+nzPffUdlnLIJ1iMauWQ/w6SRtinbbZ2KXrcgXnnjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-05T07:50:41Z"
  mac: ENC[AES256_GCM,data:3aab5WmQ9wuj6XgmWyXxVXjI+4C72AzhTX+UhrhGxIPSK/KB0YTwVIxpIO0QHL8umisZliNirEJJGqI7zhikKvAFcMl+oDqAswHW1aHDp37VPge2rhcvNxxIuQWPoiDJAPu8FGxq6rLcKAJiucyzvy1l0jWabq7ysNsVbTiWxPs=,iv:9OIZ5BRfsptwG7TMo64px91eVa0xRfjYCmX8q3coBM8=,tag:Llf/E/5AqUmX3ioNRuOIrQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
