configs:
  loki_config:
    name: loki_config_${DEPLOY_VERSION}
    file: ./config/loki/loki.yml
  alloy_config:
    name: alloy_config_${DEPLOY_VERSION}
    file: ./config/alloy/config.alloy
  alloy_entrypoint:
    name: alloy_entrypoint_${DEPLOY_VERSION}
    file: ./config/alloy/entrypoint.sh
