configs:
  logging_loki_config:
    name: logging_loki_config_${DEPLOY_VERSION}
    file: ./config/loki/loki.yml
  logging_alloy_config:
    name: logging_alloy_config_${DEPLOY_VERSION}
    file: ./config/alloy/config.alloy
