{
 "title": "Borgmatic Logs",
 "description": "Borgmatic Logs & Stats",
 "tags": [
  "borgmatic",
  "loki"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Started Backups",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"Started backup\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"Backup created.\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"Failed backup\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Time of Last Successful Backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"Backup created.\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Size of Backup Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (label_name) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |= `All archives: ` | regexp `(?P<archive_type>All archives|This archive):\\s+(?P<original_size>\\d+\\.\\d{2}) (?P<original_unit>PB|TB|GB|MB)\\s+(?P<compressed_size>\\d+\\.\\d{2}) (?P<compressed_unit>PB|TB|GB|MB)\\s+(?P<deduplicated_size>\\d+\\.\\d{2}) (?P<deduplicated_unit>PB|TB|GB|MB)` | line_format `{{ if eq .deduplicated_unit \"MB\" }}{{ mulf .deduplicated_size 1024 1024 }}{{ else if eq .deduplicated_unit \"GB\" }}{{ mulf .deduplicated_size 1024 1024 1024 }}{{ else if eq .deduplicated_unit \"TB\" }}{{ mulf .deduplicated_size 1024 1024 1024 1024 }}{{ else if eq .deduplicated_unit \"PB\" }}{{ mulf .deduplicated_size 1024 1024 1024 1024 1024 }}{{ end }}` | pattern `<deduplicated_size_byte>` | unwrap deduplicated_size_byte [$__interval]))"
    },
    {
     "expr": "last_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |= `All archives: ` | regexp `(?P<archive_type>All archives|This archive):\\s+(?P<original_size>\\d+\\.\\d{2}) (?P<original_unit>PB|TB|GB|MB)\\s+(?P<compressed_size>\\d+\\.\\d{2}) (?P<compressed_unit>PB|TB|GB|MB)\\s+(?P<deduplicated_size>\\d+\\.\\d{2}) (?P<deduplicated_unit>PB|TB|GB|MB)` | unwrap deduplicated_unit [$__interval])"
    }
   ]
  },
  {
   "title": "Borgmatic Recent Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} "
    }
   ]
  }
 ]
}