{
 "title": "Borgmatic Backups",
 "description": "Borgmatic backup monitoring",
 "tags": [
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Runs (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(borgmatic_backup_runs_total[24h])))"
    }
   ]
  },
  {
   "title": "Successful Backups (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(borgmatic_backup_successes_total[24h])))"
    }
   ]
  },
  {
   "title": "Failed Backups (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(borgmatic_backup_failures_total[24h])))"
    }
   ]
  },
  {
   "title": "Last Successful Backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(borgmatic:backup_last_success_age_seconds)"
    }
   ]
  },
  {
   "title": "Last Archive Footprint",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(borgmatic_last_archive_deduplicated_bytes)"
    }
   ]
  },
  {
   "title": "Total Repo Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borgmatic_repository_deduplicated_bytes"
    }
   ]
  },
  {
   "title": "Deduplicated Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "borgmatic_last_archive_deduplicated_bytes != borgmatic_last_archive_deduplicated_bytes offset 30s",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "borgmatic_last_archive_duration_seconds != borgmatic_last_archive_duration_seconds offset 30s",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Borgmatic Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{service=\"backup_borgmatic\", node=~\"$node\"}"
    }
   ]
  }
 ]
}