{
 "title": "Crowdsec Cyber Threat Insights",
 "description": "Cyber threat insights with CrowdSec, Loki and Grafana",
 "tags": [
  "cyberthreat",
  "crowdsec"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({job=\"crowdsec\"}, instance)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cyberthreats Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, country, asname, asnumber, iprange, ip, type) (count_over_time({job=\"crowdsec\", instance=~\"${host:raw}\"} | country != \"\" | keep instance, country, asname, asnumber, iprange, ip, type [$__range]))"
    }
   ]
  },
  {
   "title": "Top 10 Cyberthreat Countries",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (country) (count_over_time({job=\"crowdsec\", instance=~\"${host:raw}\"} | country != \"\" | keep country [$__range])))"
    }
   ]
  },
  {
   "title": "Cyberthreats Map",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (country, longitude, latitude) (count_over_time({job=\"crowdsec\", instance=~\"${host:raw}\"} | country != \"\" | keep country, longitude, latitude [$__range]))"
    }
   ]
  },
  {
   "title": "Realtime Cyberthreats: ${__from:date:YYYY-MM-DD HH:mm:ss} - ${__to:date:YYYY-MM-DD HH:mm:ss} / Granularity: $__interval",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{job=\"crowdsec\", instance=~\"${host:raw}\"}"
    }
   ]
  }
 ]
}