GATUS_DB_PASSWORD: ENC[AES256_GCM,data:r5WpS1PewvbB4oXs0/Xer4akcZP0sysYwhIv2GmGbXzXTiWVPxMQ0dba34jl2IsMqSp6gf1vig0QQe5XRINjqg==,iv:eezYpPlMu9TlXSQzPxyj3XeFVcm7nENTt4CuXqvGlqA=,tag:/a8brMjoLzz8TfIhYImC4g==,type:str]
GATUS_HASS_TOKEN: ENC[AES256_GCM,data:VnOBPVuKBlDIdioJAjSWCIyX0tku0OCiXb1DeRqjXgaC2WX7xkV53ptxIg30I47LYIdKZCTymz78X5XI1ZI97giv1kYN2rf1eKdCAgIHyiRdScIJ9Gm4XqnlByDjPh0fXkzglv58ilSwzr41IQew6PjykPHcHtpHS9sY9Fcut+KJBDkugEU9RwdOjlr3nb6wqkHLstH6vi7jLnf1vNsgKPJ3MmplEE2tuYyJ7F+VhKBK3NDHGz7U,iv:vV/JfNvTz7/cVHQ13s0g+SIa9h6dgxVqHXC3D/m6Vn8=,tag:Ppf7FcJe/NhCqj4bY5iSug==,type:str]
GATUS_PROXY_URL: ENC[AES256_GCM,data:4yfeIa0Gwca1Ghmcb2/ekAGYHYQLDMTrIxvuNkOa8tdnO5NoMkY/NdW5SMx1EDE3rOJiTw==,iv:vLwqFFltJLG+vDEDEUkGzegojQ1zjpdKuI1SnpxqsRw=,tag:tsVqGs3AUQX+JTnOHvgXlg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VzdBbEFsYW9VeStHZkJU
        STRCMmU0blQ4SEdPdWJ3TEtGQkVyMWxLOVRzCjZTQVZ6RzRmR3F3SWJzWHFMSGZl
        cVRLd0R2eWF6dmo2TEVDa0VmM0w4cWcKLS0tIE9zT0JzbUNwL3YrV3FId0VreWxt
        alJ1Z0E4c0V6dG05UmE5ejNIdVE1SmMK4YudtfeIbZ+z2fPZJAfz/o3Dz+hqIB9C
        4o+9OjEA5Kb5kHCeNrdbEOozxCPjTsjDyZqYRZpLSq4BCquTMuemUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T08:03:47Z"
  mac: ENC[AES256_GCM,data:yV/ju+c8zbRy2sKXCGQLr9cAfvfMQLwf0FGQe+Wb9QALb1CY8dfb/u1Y/6FaBaj4M1vEb4xbWCYPBWWrDg7ZHnU578VT3neKfLZh65yEBcP6XPx4PRuo1TqEWIZxedpW4sgJvhWompTahjmbkgXTst2tyJtK+MHpYZE2ElWwAYs=,iv:UsWrvhPEynWcHDOScGhdpBR88zuuZ49EJAH4OSN50hY=,tag:MCriOMObL92Tw8I+qqHdbw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
