# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

include:
  - configs.yml

services:
  pinchflat:
    image: keglin/pinchflat:latest
    entrypoint: ["/bin/sh", "/init.sh"]
    logging:
      <<: *logging
    stop_grace_period: 30s
    environment:
      - PINCHFLAT_OWNER=${GLOBAL_NONROOT_DOCKER}
      - YT_DLP_WORKER_CONCURRENCY=2
      - TZ=${GLOBAL_TZ_LOCAL}
      - JOURNAL_MODE=wal
      - LOG_LEVEL=info
    configs:
      - source: pinchflat_init
        target: /init.sh
    networks:
      - infra_gw-internal
    volumes:
      - pinchflat-data:/config
      - cifs-youtube:/downloads
    deploy:
      <<: [*place-vm, *deploy]
      update_config:
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.scope.internal=true"
        - "traefik.http.routers.pinchflat.rule=Host(`pinchflat.${DOMAIN_PRIVATE}`)"
        - "traefik.http.routers.pinchflat.entrypoints=websecure"
        - "traefik.http.services.pinchflat.loadbalancer.server.port=8945"
        - "homepage.group=Applications"
        - "homepage.name=Pinchflat"
        - "homepage.icon=pinchflat"
        - "homepage.href=https://pinchflat.${DOMAIN_PRIVATE}"
        - "homepage.description=YouTube Media Manager"
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-large

volumes:
  pinchflat-data:
  cifs-youtube:
    driver: local
    driver_opts:
      type: cifs
      device: //${GLOBAL_CIFS_HOST}/media/youtube
      o: "username=${GLOBAL_CIFS_USERNAME},password=${GLOBAL_CIFS_PASSWORD},uid=${GLOBAL_NONROOT_PUID},gid=${GLOBAL_NONROOT_PGID},iocharset=utf8"

networks:
  infra_gw-internal:
    external: true
