# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

include:
  - configs.yml

services:
  pinchflat:
    image: keglin/pinchflat:latest
    entrypoint: ["/bin/sh", "/init.sh"]
    logging:
      <<: *logging
    stop_grace_period: 30s
    environment:
      - PINCHFLAT_OWNER=${GLOBAL_NONROOT_DOCKER}
      - LOG_LEVEL=info
    configs:
      - source: pinchflat_init
        target: /init.sh
    networks:
      - infra_gw-internal
    volumes:
      - pinchflat-data:/config
      - cifs-media:/downloads
    deploy:
      <<: [*place-vm, *deploy]
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.scope.internal=true"
        - "traefik.http.routers.pinchflat.rule=Host(`youtube.${DOMAIN_PRIVATE}`)"
        - "traefik.http.routers.pinchflat.entrypoints=websecure"
        - "traefik.http.services.pinchflat.loadbalancer.server.port=8945"
        - "homepage.group=Media"
        - "homepage.name=Pinchflat"
        - "homepage.icon=pinchflat"
        - "homepage.href=https://youtube.${DOMAIN_PRIVATE}"
        - "homepage.description=YouTube Downloader"
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-large

volumes:
  pinchflat-data:
  cifs-media:
    driver: local
    driver_opts:
      type: cifs
      device: //${GLOBAL_CIFS_HOST}/media
      o: "username=${GLOBAL_CIFS_USERNAME},password=${GLOBAL_CIFS_PASSWORD},uid=${GLOBAL_NONROOT_PUID},gid=${GLOBAL_NONROOT_PGID},iocharset=utf8"

networks:
  infra_gw-internal:
    external: true
