# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    logging:
      <<: *logging
    stop_grace_period: 30s
    command:
      - "--docker=unix:///var/run/docker.sock"
      - "--docker_only=true"
      - "--disable_metrics=referenced_memory,tcp,udp,advtcp,sched,hugetlb,resctrl"
      - "--housekeeping_interval=15s"
    networks:
      - infra_metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      <<: *deploy
      update_config:
        order: start-first
      mode: global
      resources:
        <<: *resources-small

networks:
  infra_metrics:
    external: true
