# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

include:
  - configs.yml

services:
  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    entrypoint: ["/bin/sh", "/etc/cadvisor/entrypoint.sh"]
    logging:
      <<: *logging
    stop_grace_period: 30s
    configs:
      - source: cadvisor_entrypoint
        target: /etc/cadvisor/entrypoint.sh
    command:
      - "--docker=unix:///cadvisor-proxy/docker.sock"
      - "--docker_only=true"
      - "--disable_metrics=referenced_memory,tcp,udp,advtcp,sched,hugetlb,resctrl"
      - "--housekeeping_interval=15s"
    networks:
      - infra_metrics
    volumes:
      - cadvisor-proxy:/cadvisor-proxy:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      <<: *deploy
      update_config:
        order: start-first
      mode: global
      resources:
        <<: *resources-small

  cadvisor-socket-proxy:
    image: wollomatic/socket-proxy:1.11.4
    user: "0:0"
    environment:
      # HACK: forces restart on redeploy. wollomatic deletes socket on shutdown
      DEPLOY_VERSION: "${DEPLOY_VERSION}"
    logging:
      <<: *logging
    stop_grace_period: 30s
    command:
      - "-proxysocketendpoint"
      - "/cadvisor-proxy/docker.sock"
      - "-proxysocketendpointfilemode"
      - "0660"
      - "-socketpath"
      - "/var/run/docker.sock"
      - "-allowhealthcheck"
      - "-allowGET"
      - "(/v\\d+\\.\\d+/(containers/.*/json|images/json|info|version)|/_ping)"
      - "-allowHEAD"
      - "/_ping"
      - "-loglevel"
      - "WARN"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - cadvisor-proxy:/cadvisor-proxy
    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    deploy:
      <<: *deploy
      update_config:
        order: stop-first
      mode: global
      resources:
        <<: *resources-tiny

volumes:
  cadvisor-proxy:

networks:
  infra_metrics:
    external: true
