secrets:
  gateway_external_bouncer_key:
    name: gateway_external_bouncer_key_${DEPLOY_VERSION}
    external: true
  gateway_external_crowdsec_cti_key:
    name: gateway_external_crowdsec_cti_key_${DEPLOY_VERSION}
    external: true
  widget_crowdsec_password:
    name: widget_crowdsec_password_${DEPLOY_VERSION}
    external: true
  global_db_provisioner_password:
    name: global_db_provisioner_password_${DEPLOY_VERSION}
    external: true
  gateway_external_crowdsec_db_password:
    name: gateway_external_crowdsec_db_password_${DEPLOY_VERSION}
    external: true
  global_cloudflare_acme_public_token:
    name: global_cloudflare_acme_public_token_${DEPLOY_VERSION}
    external: true

configs:
  gateway_external_traefik_dynamic_base:
    name: gateway_external_traefik_dynamic_base_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/base.yml
  gateway_external_traefik_dynamic_authentik:
    name: gateway_external_traefik_dynamic_authentik_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/authentik.yml
  gateway_external_traefik_dynamic_bouncer:
    name: gateway_external_traefik_dynamic_bouncer_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/bouncer.yml
  gateway_external_traefik_dynamic_geoblock:
    name: gateway_external_traefik_dynamic_geoblock_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/geoblock.yml
  gateway_external_traefik_dynamic_hass_public:
    name: gateway_external_traefik_dynamic_hass_public_${DEPLOY_VERSION}
    file: ./config/traefik/dynamic/hass-public.yml
  gateway_external_crowdsec_entrypoint:
    name: gateway_external_crowdsec_entrypoint_${DEPLOY_VERSION}
    file: ./config/crowdsec/entrypoint.sh
  gateway_external_crowdsec_acquis:
    name: gateway_external_crowdsec_acquis_${DEPLOY_VERSION}
    file: ./config/crowdsec/acquis.yaml
  gateway_external_crowdsec_profiles:
    name: gateway_external_crowdsec_profiles_${DEPLOY_VERSION}
    file: ./config/crowdsec/profiles.yaml
  gateway_external_crowdsec_config:
    name: gateway_external_crowdsec_config_${DEPLOY_VERSION}
    file: ./config/crowdsec/config.yaml
  gateway_external_crowdsec_console:
    name: gateway_external_crowdsec_console_${DEPLOY_VERSION}
    file: ./config/crowdsec/console.yaml
  gateway_external_crowdsec_notifications:
    name: gateway_external_crowdsec_notifications_${DEPLOY_VERSION}
    file: ./config/crowdsec/notifications-http.yaml
  gateway_external_crowdsec_whitelist_rejected:
    name: gateway_external_crowdsec_whitelist_rejected_${DEPLOY_VERSION}
    file: ./config/crowdsec/whitelist-rejected.yaml
  gateway_external_init_db:
    name: gateway_external_init_db_${DEPLOY_VERSION}
    file: ./config/bootstrap/init-db.sh
