GATEWAY_EXTERNAL_AUTHENTIK_URL: ENC[AES256_GCM,data:gqcqqn1g6QqEPEEdh7All+RAjJB4+a7+ZIhTUn2H/uLhaF9BF2FcNYaUs5b3+CxSezCBPBN2TscDnjTWAEUiaIODx6BsGScCyw==,iv:ARQqEa5ZNuInCcD8P5RGQTqUzh4A1hQ+1tAY3MOHrYw=,tag:uqRaDYWogCXjuRzIFwmJCw==,type:str]
GATEWAY_EXTERNAL_GEOBLOCK_TOKEN: ENC[AES256_GCM,data:CrO9vONlvga4ScyxR1hfjZM4371zfy9FdXhUmbYCmfa4Opio3ZTblA1u9grGOddEnpE3Tk7x5ZajlwBz3aW0rg==,iv:0/qVk++bBAT34raXMyUVkaha2DHEtdN/SB1mRlNvbcM=,tag:5OPd5RrV1ugF/pgM69cbGg==,type:str]
GATEWAY_EXTERNAL_BOUNCER_KEY: ENC[AES256_GCM,data:IPTWpbD12u3YIQzMMF2y1XJ7IL7hmRBNPaeL1/+2/aLlsnX0gGku4NZ7,iv:TtYFNIwXTNitIl98gZ7AZEh0fukNCCbrNJlBjF7PDrg=,tag:Q5dTfaZOirpRO5rh1rnrkg==,type:str]
GATEWAY_EXTERNAL_CROWDSEC_CTI_KEY: ENC[AES256_GCM,data:pQIUbm5EVT/diEtdUGkNF6R5z2A3jmdxoJXPF69vKWVj4LujReLYKQ==,iv:rUZOAZ3VIIb2wgiyeZvGCyic4l4B82ULzQYXu+HANHk=,tag:gImVfsgA47RJMUDFQR3qcQ==,type:str]
GATEWAY_EXTERNAL_CROWDSEC_ENROLL_KEY: ENC[AES256_GCM,data:48T/ohk/fUUu/v+20D84dUAKqQgFHQuvOA==,iv:FeG91Ha/0YQTr+97vjx00km8kdP1VaJgnRZLzqYSb+o=,tag:6+IKzkE8ykwrxczgf2sABg==,type:str]
GATEWAY_EXTERNAL_CROWDSEC_AUTOREG_TOKEN: ENC[AES256_GCM,data:O5j34lqjU5cdmEeVFifa0IRYKUtfvJ4Ior5ERXQu7jgfZGs=,iv:g8U7aHSolvPDaY7JSSeohsrBlRhJvJttE9KdAyD9GLA=,tag:hH2+cEQrER5OYl7WZZ1XFg==,type:str]
GATEWAY_EXTERNAL_CROWDSEC_DB_PASSWORD: ENC[AES256_GCM,data:dw37qiA2lSih3VMaQq71WIIYwoD9hwnQ7K8xRpuzmxGKt7vWdzXLkt7vg8CHRebHDA1rGjpDVEJAqIqlhBFRIw==,iv:DamGW7mc4bwRbyYXpg574DrPnT8kDu6eToXTmNpVVRQ=,tag:bjs53cBZqZBFEsJ2wTDEfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL3NjM1FLMkIzT0g3SUsz
        WEJQVUhuOXlxTEZaK3lLMXpRYWRMT2lQVkhZCmxvaW5qZjEzSmpSK2c0RXFKeUJo
        YXpidVIxa08zZnVQcnIxQ21NWksra3MKLS0tIDdLVmp5YVUra0xtR05wRkFJMmM2
        WWRNTXMrMk8reTJZdng5Q0xSWkowMUEK7sk6bMZt/ShoOpLI2lMKC7D/0JLfw5RW
        DfZhpTDqsojUkmrexgNNLuxp6I8U5EezJ8uIukChPcoEbKtMdbSQqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T19:18:04Z"
  mac: ENC[AES256_GCM,data:e+5GbPyWnC0iwU/+XpAOHo6JkA/qTsnEkfD5SXkR3DqSmwBAiWTPN6JIX1/pLfEPN1YGZ8uPFvsYThiV1Szt1d8SKsU0xzDg3asrmDyjx41ThnGErMitUA876KVXGqB/eKQ3NOqHqUnUMGAQVIiTyOsqLngQG6KbwA7gJJdjaU0=,iv:gyZiD3+8pnwdyxhJTMwd+WiBNjz/hvz8jcMXrPTby1c=,tag:aQgs3uR/PsAjbOo5FFft1g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
