AUTHENTIK_URL: ENC[AES256_GCM,data:xgqRf0NDO8cVBp+NDem3vnCXttrPfO/7RWFYjQ+fexqbM7uJL9LZF63Z1vhlrA5k7IAncJkuh4/A6Ol/w6jkrbbEqDX9PgWwBA==,iv:chxG7b35cSzItZ8704kHv/KWCtTlqFzBwIS0LWzVw74=,tag:BeY/XKoQF2CH05y+fEBMsA==,type:str]
GEOBLOCK_IP2LOCATION_TOKEN: ENC[AES256_GCM,data:3S6Y4h0dsejyGhk5J1K/hWQDZZVJUSiElpNSq/xfma3WAw1b66S67jNHasIwePkyGUnr8Xelv5wimqo1zHT/2Q==,iv:IDZdPFSI5+8I95VLSknU4gw8pET25NJiMs/bOxvYK44=,tag:FVF83hdkaap9/Is1XzCQIg==,type:str]
BOUNCER_KEY_TRAEFIK: ENC[AES256_GCM,data:O5jB7I5gNCfFcbde+zS9bSBDK99nysmUq8XdKPKTgCk8HhLrDGlrx9vY,iv:nJUR1gV8fDxah75uxr74vpRk4yAOm8bjfpHsFf6Amr4=,tag:aaKecuOkxG+f79ARPb3B7Q==,type:str]
CROWDSEC_CTI_KEY: ENC[AES256_GCM,data:IJuAVgItlDt4+y16CmV8YBRdE+l7HzkottXatINE2tZnu6JzFOXO7A==,iv:0ati+Xe1YmOghMmnA5HkoJWWdaaKIqT5YLVGDXnZLDI=,tag:Zy8kwmf9/80y55Uaj1bDew==,type:str]
CROWDSEC_ENROLL_KEY: ENC[AES256_GCM,data:XSw5TGFrkxaLXlUF39O3H/whw/APE1tPuQ==,iv:HMcrmH+BS+4BVKoR/Tow+yh81B20+39SZSEhDkWKZG0=,tag:V7Rt/Lc+03rPEzFHrn5JZA==,type:str]
CROWDSEC_AUTOREG_TOKEN: ENC[AES256_GCM,data:8AZABw74leMErJMoEN1kh0z0E7BWTkrZ4bJxJOMNsqL5VDg=,iv:csI6gYY0kIRCYj9y5VIyGzpEoLEarUqLXiOhxZyilrM=,tag:d2rERrOxsmuzqy0R0zZOhg==,type:str]
CROWDSEC_POSTGRES_PASSWORD: ENC[AES256_GCM,data:6c14hVzaOIvJAAu9HRI4WrKuxdsdUc4hlZWNpr9PZs+btB+Z/Ze424eny/1pt1ztYlR3NaZLjZ0ZwuqIyyquxg==,iv:lKw3aKNM7Whrc/SDHE4VLn1tk9cm88EK1I/zk6PJeBc=,tag:2ZMg1R0rShcujbGFx94NSA==,type:str]
CROWDSEC_HOMEPAGE_USERNAME: ENC[AES256_GCM,data:gDjGxwy1FFA=,iv:PbZCEa3ynxdJqGJQ0jTH+gbuXRDhrOlkX/BvXmJstrw=,tag:+8BAj1ZQroAkePTtUCA0fQ==,type:str]
CROWDSEC_HOMEPAGE_PASSWORD: ENC[AES256_GCM,data:6YaZFDWaojguSi8Cdi6CIRCw9YGRvF4mR4hMuNXRpFHAhar7Z+VF4EG4HFnRhDMuX19r/G1Par0TMgLjw1sc3g==,iv:Sqtj3TVxP+JlbIEd5usK8TvHQpKbdzkz9ywdQmPDDec=,tag:i6JAZx0Hp7elOR0f2LKMLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L1RZbWpWY2c2V2I3REtR
        SllmWlJwTEp2aUhLd1F4bjAyRTEyT0FMckRNCjJlS0JVTHVxR0ZDTTAwMENUNFp4
        VUlFTHpjY3F5OUQ5OE9vd0V6cUlESGsKLS0tIHZUSUx3VEpqdXREMGhxZ04xZjk5
        MHRGa0VmVGU3cXNNbkZWTDZySUVROGcKNvp7aEqKkSTtZFg1Gf9/dKQUCwK2Dinl
        OpUxKHgl+PhC5s8GtmaIUQZy09Ut7Um0pQesozbA4QHgcR6YD2BBqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-05T07:50:42Z"
  mac: ENC[AES256_GCM,data:F++n1Ryu1atrRE4xSKa/VAcCrdxJvla2Tsc0GzDL8PhRiVostk8KYroQU1hyPn0cqIIRjsc6vvrMDaMU0Bf16WmaWGgGagdOQxHcS8J7tX/qcb2iei5z/L1f149vT/6MCuQk6uOeu9Rut/rCf4/IvnZ8stgmA8DeZLqsP/UB5N0=,iv:ntYJ9uDAHA4hXR+We27YQeHwE/iXM5uMVQv13h6XoQ0=,tag:ud+dG21Wgpwe6dCmJF6JYw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
