# CrowdSec Local API Configuration
api:
  cti:
    key: ${GATEWAY_EXTERNAL_CROWDSEC_CTI_KEY}
    enabled: true
    log_level: info
  server:
    log_level: warn
    listen_uri: 0.0.0.0:8085

prometheus:
  enabled: true
  listen_addr: 0.0.0.0
  listen_port: 6060

db_config:
  log_level: info
  type: pgx
  host: postgres
  port: 5432
  db_name: crowdsec
  user: crowdsec
  password: ${GATEWAY_EXTERNAL_CROWDSEC_DB_PASSWORD}
  sslmode: disable
  flush:
    max_items: 40000
    max_age: 56d
