---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3-file-provider.json

http:
  middlewares:
    authelia:
      forwardAuth:
        address: '{{ env "AUTHELIA_URL" }}'
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
