# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  syncthing:
    image: syncthing/syncthing:latest
    logging:
      <<: *logging
    stop_grace_period: 30s
    environment:
      - PUID=${GLOBAL_NONROOT_PUID}
      - PGID=${GLOBAL_NONROOT_PGID}
      - STGUIAPIKEY=${SYNCTHING_API_KEY}
    networks:
      - infra_gw-internal
      - infra_metrics
    volumes:
      - syncthing-data:/var/syncthing
      - cifs-personal:/mnt/personal
      - cifs-photos:/mnt/photos
    healthcheck:
      test: ["CMD", "curl", "-fkLsS", "-m", "2", "http://127.0.0.1:8384/rest/noauth/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      <<: [*place-main, *deploy]
      update_config:
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.scope.internal=true"
        - "traefik.http.routers.syncthing.rule=Host(`syncthing.${DOMAIN_PRIVATE}`)"
        - "traefik.http.routers.syncthing.entrypoints=websecure"
        - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        - "traefik.tcp.routers.syncthing-sync.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.syncthing-sync.entrypoints=syncthing-tcp"
        - "traefik.tcp.routers.syncthing-sync.service=syncthing-sync"
        - "traefik.tcp.services.syncthing-sync.loadbalancer.server.port=22000"
        - "traefik.udp.routers.syncthing-sync.entrypoints=syncthing-udp"
        - "traefik.udp.routers.syncthing-sync.service=syncthing-sync"
        - "traefik.udp.services.syncthing-sync.loadbalancer.server.port=22000"
        - "homepage.group=Applications"
        - "homepage.name=Syncthing"
        - "homepage.icon=syncthing"
        - "homepage.href=https://syncthing.${DOMAIN_PRIVATE}"
        - "homepage.description=File Synchronization"
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-large

volumes:
  syncthing-data:
  cifs-personal:
    driver: local
    driver_opts:
      type: cifs
      device: //${GLOBAL_CIFS_HOST}/personal
      o: "username=${GLOBAL_CIFS_USERNAME},password=${GLOBAL_CIFS_PASSWORD},uid=${GLOBAL_NONROOT_PUID},gid=${GLOBAL_NONROOT_PGID},iocharset=utf8"
  cifs-photos:
    driver: local
    driver_opts:
      type: cifs
      device: //${GLOBAL_CIFS_HOST}/photos
      o: "username=${GLOBAL_CIFS_USERNAME},password=${GLOBAL_CIFS_PASSWORD},uid=${GLOBAL_NONROOT_PUID},gid=${GLOBAL_NONROOT_PGID},iocharset=utf8"

networks:
  infra_gw-internal:
    external: true
  infra_metrics:
    external: true
