"groups":
- "name": "node-exporter.rules"
  "rules":
  - "expr": |
      count without (cpu) (
        count without (mode) (
          node_cpu_seconds_total{job="node"}
        )
      )
    "record": "instance:node_num_cpu:sum"
  - "expr": |
      1 - avg without (cpu, mode) (
        rate(node_cpu_seconds_total{job="node", mode="idle"}[1m])
      )
    "record": "instance:node_cpu_utilisation:rate1m"
  - "expr": |
      (
        node_load1{job="node"}
      /
        instance:node_num_cpu:sum{job="node"}
      )
    "record": "instance:node_load1_per_cpu:ratio"
  - "expr": |
      1 - (
        node_memory_MemAvailable_bytes{job="node"}
      /
        node_memory_MemTotal_bytes{job="node"}
      )
    "record": "instance:node_memory_utilisation:ratio"
  - "expr": |
      1 - (
        node_filesystem_avail_bytes{job="node", fstype=~"ext4|xfs|btrfs|zfs"}
      /
        node_filesystem_size_bytes{job="node", fstype=~"ext4|xfs|btrfs|zfs"}
      )
    "record": "instance_mountpoint:node_filesystem_utilisation:ratio"
  - "expr": |
      sum without (device) (
        rate(node_network_receive_bytes_total{job="node", device!~"lo|docker.*|veth.*|vx-.*|br-.*"}[1m])
      )
    "record": "instance:node_network_receive_bytes:rate1m"
  - "expr": |
      sum without (device) (
        rate(node_network_transmit_bytes_total{job="node", device!~"lo|docker.*|veth.*|vx-.*|br-.*"}[1m])
      )
    "record": "instance:node_network_transmit_bytes:rate1m"
