# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  socket-proxy:
    image: wollomatic/socket-proxy:1
    read_only: true
    user: "65534:989" # GID should be that of the "docker" group on the host
    cap_drop: [ALL]
    security_opt: [no-new-privileges]
    logging:
      <<: *logging
    stop_grace_period: 30s
    command:
      - '-listenip=0.0.0.0'
      - '-allowfrom=0.0.0.0/0'
      - '-allowhealthcheck'
      - '-stoponwatchdog'
      - '-watchdoginterval=600'
      - '-loglevel=info'
      - '-allowGET=/(v1\..{1,2}/)?(_ping|version|containers/.*|events.*|services.*|tasks.*|networks.*|nodes.*|volumes.*|images.*|info|configs.*|secrets.*|swarm.*|system.*)'
      - '-allowHEAD=/_ping'
    networks:
      - infra_socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      <<: *deploy
      update_config:
        order: start-first
      placement:
        constraints:
          - node.role == manager
          - node.labels.type == vm
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-tiny

networks:
  infra_socket:
    external: true
