# Traefik Dynamic Configuration - Base Routes & Middlewares
# https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/file.yaml
---
# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3-file-provider.json

http:
  routers:
    catch-all:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - websecure
      priority: 1
      service: catch-all

  services:
    catch-all:
      loadBalancer:
        servers: []

  middlewares:
    security-headers:
      headers:
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customResponseHeaders:
          Server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: strict-origin-when-cross-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
