DOMAIN_PUBLIC: ENC[AES256_GCM,data:iL6vTGy2k0dr+Q==,iv:5JpRTiFNhEQxjytFCRm1BvP+oAT/xrQWJDK1wFvOEDo=,tag:4zYI3YxMwoowuNUAYpq27g==,type:str]
DOMAIN_PRIVATE: ENC[AES256_GCM,data:5tK/DPL1kUW9drRBa4ScpLJN,iv:qYI55aeaNbHuMiBGhy1iUBIrOe0rzNrWUB4UF25O3gQ=,tag:5uEOIfX7YU8b8txYUjd+9Q==,type:str]
GLOBAL_OIDC_URL: ENC[AES256_GCM,data:FUpSTrPYz3atKgODfHLB,iv:80cdklmhUmP986AaEkDpbTkJQjix2nz9qHXzFJu0LPc=,tag:lHDH/oMMECsWNKV4/Htd/A==,type:str]
GLOBAL_LDAP_BASE_DN: ENC[AES256_GCM,data:Bc2QGa1KGBcOVD4n2d5DBQ==,iv:YUSWfbkIHNS0TqLvoJjpV8fRLO4FO6MApb2diIAXk7c=,tag:0PuC7adi/Lk3B8Za/dXIaQ==,type:str]
sops:
    age:
        - recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNanVsSWYrTUoyMHV3R2py
            TThZa2haNlB1eVVQbUcyUC8xcEY4cXlTMFZNCjU3cVJ6MFlFcEh5czc4TlovbkRD
            aEJkQmFJKzBVVG9pZ3JxQnM1YVAydjgKLS0tIEVNMk5kOXFPRFNrNlBiUS9VTEU4
            K0ZpWWYzKzNpQ3Vaak9DODhvOWh0clUK3cc9Y0VS8J0vQEU7xaJHqm1hn4mEcTok
            xvwbvJvWSliItwMO823oD5jvyw27g1/K/kfnGuOq1F8BdACevR1+rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:23:47Z"
    mac: ENC[AES256_GCM,data:scCPA7PIrqJdsxvhymNp8vQK6B1HDUQNFP6q9O8x2FS5SBOWCLEcMJMbhB/uWVOD3qooiSfYzqW2OUayLllWHf4kEoPnxcLXjQdI9BpuEgkF0HTtUPd3JIaALmnjDfAzUDVtUSlZ6JhsKqVHvpw8z6ehq6qhJAhYE/kfBnzqLa4=,iv:cBeWUTwj+1IthpXPVJRjkx5QbgFIiAc5Q3WeZFrss9U=,tag:q0tPkKQfLYl/pIH2HUEf4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
