DOMAIN_PUBLIC: ENC[AES256_GCM,data:ZLi+29wTKau6vg==,iv:2cKLbDj5I90xC0UZM1rNN4VhAotuebpTJR2LzmPCRkA=,tag:Vr5xMuAZXsILKci1ERI0wg==,type:str]
DOMAIN_PRIVATE: ENC[AES256_GCM,data:KE7Fg7ru2Fg7Vrsn,iv:8ziOw7VTAN46UUMoYVVoYUKEoM6R8lumQEDLeL3udLo=,tag:ummrhhubqsb489EGeRxiHw==,type:str]
GLOBAL_OIDC_URL: ENC[AES256_GCM,data:ytOqKRo3PPZgF4712wRd,iv:ZbhIf32d9tNIxzvv3gO+Z4UHhWGwv9XUM5BkuJrXj+Q=,tag:HqbohLj3f+NVnLcpvqGEmQ==,type:str]
GLOBAL_LDAP_BASE_DN: ENC[AES256_GCM,data:Sf7tFM9Dsat4CC4whZ5p5A==,iv:T8higBGknhe9ph2o43dESGRf8vAWT+OmVe2D89YutFk=,tag:ymrQeCh9YSdUbfVDHCQ3LQ==,type:str]
GLOBAL_CIFS_HOST: ENC[AES256_GCM,data:YXltH/TNsjK6Bw==,iv:nC79MjOOn4u3yWCZSVupa3drtaDA1lbEoMjDMN+aPsE=,tag:owJlhShd8ENOzOtHSav3+w==,type:str]
GLOBAL_CIFS_PASSWORD: ENC[AES256_GCM,data:3xrudOYkVeREP4Ft5s4VeJkGPA==,iv:gwKM5R460nlwVbK1YAvHKrI+1MeitHfj6+/mPfWGcSw=,tag:So++aeMmTefbX/Ufk7DltQ==,type:str]
GLOBAL_CIFS_USER: ENC[AES256_GCM,data:rPQn1oYK,iv:I2MaI+MDruDluIMv/AQiSAShr73hU3rSM5Ka03wOx/Q=,tag:aXYaTQKpms86VRlzwstUmg==,type:str]
GLOBAL_CLOUDFLARE_ACME_PUBLIC_TOKEN: ENC[AES256_GCM,data:aCqhTBIIh4pa0dm0AFAOVhd/Vo+caIjY3SNR1+GRrpcT8qAHMeY6GA==,iv:d/q4uFWGNA6VN+Q3CDlF3r+ntDvm85WUpoVD6xoNjxY=,tag:iPsRcV9kLILon37gcgQ6Ig==,type:str]
GLOBAL_CLOUDFLARE_ACME_PRIVATE_TOKEN: ENC[AES256_GCM,data:XNKo1IkfvvZYeHhfaQgNit12hVy0jllp1EjOlqFVJqta+a3U0y1iNQ==,iv:53SpmlN1ui72fPVuVnTjLM4wLt+yIi/gex9BV8QMsBo=,tag:wYeq5MozmID/+FBZ9PKD0A==,type:str]
GLOBAL_VPS_IP_PUBLIC: ENC[AES256_GCM,data:4RU18FsUZr/odVqoyw==,iv:6ntwds7fyf03rhwCcOs4WSHUlJB93myj/KsebLZvFMQ=,tag:2Ta7zaydLecyGIYzkjKfHw==,type:str]
GLOBAL_VPS_IP_TUNNEL: ENC[AES256_GCM,data:+zpndKAu+OWtN8FT,iv:sOCGFbr/3mB2AP2343hq4Ybw8TKDGyUhelS8hKmcvFo=,tag:jFLPIyZuLS13+QBQP+rpNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZVRzdGh1c1NERVoyNlhX
        bHNncnM1UUJxak4ySUFhWWNobnZCbDJ6Q0FvCkxLWmMvREhWbXBaVHlFV3lmYU9B
        K3ZBOWhRQ2IvMTk0dTNtODkybGdJRjgKLS0tIC81M1lrNUlaNHlIQlhkY1M0S3dY
        WU9UN3c4dXdtdzVxZi9zUEU5aURqOWsK+x3xlx42tV5OAbIKlsMZ14tT26/EzBvH
        ycZaXMbwg4AYDO3QP2WpRAQRRtDYSMJCN8u2EPy1CAzTypBToqn+pw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-10-06T22:09:11Z"
  mac: ENC[AES256_GCM,data:FkPBmldzC0a8nhSK2XhMiDTz7A1/I7HzjZlEoTGxP5+yoFewk8YoUqX0o/Y/0q74CQnUjlc7dBUR9l52S/0DKeqMr9NwEcbikRBPnCFMX6Ay5E42GcyljlUL84CUV80qN3Bg2PzZDv3BzWwXgytbJco1xOrvzSodZ/Kn1QpbHww=,iv:z0IWxBjYGZQIGI/W8+ArYg9MoGGS0AYapfaqy5G2+yE=,tag:CtU/DqXgQxQd5btYt1LwdQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
