key_file="" # Using seed, key_file is empty to avoid warnings
verbose=false
ldap_host = "0.0.0.0"
ldap_port = 389
http_host = "0.0.0.0"
http_port = 17170
force_ldap_user_pass_reset = "always"
ignored_user_attributes = []
ignored_group_attributes = []

[smtp_options]
port=465
smtp_encryption = "TLS"
enable_password_reset=true

[ldaps_options]
enabled=false
