# Swarm secrets for gateway-internal stack
# Included via docker compose include directive

secrets:
  cloudflare_dns_api_token_internal:
    name: cloudflare_dns_api_token_internal_${DEPLOY_VERSION}
    external: true
