#:schema https://mise.jdx.dev/schema/mise.json

[env]
_.file = { path = "{{ env.PROJECT_SECRETS_DIR }}/prod.yaml", redact = true }

SWARM_SSH_USER = "root"
SWARM_HOST = "ssh://{{ env.SWARM_SSH_USER }}@swarm-vm"

GLOBAL_SWARM_OCI_REGISTRY = "registry.{{ env.DOMAIN_PRIVATE }}"
GLOBAL_ACME_CA_SERVER = "https://acme-v02.api.letsencrypt.org/directory"
