secrets:
  registry_http_secret_key:
    name: registry_http_secret_key_${DEPLOY_VERSION}
    external: true
  registry_htpasswd:
    name: registry_htpasswd_${DEPLOY_VERSION}
    external: true

configs:
  registry_init:
    name: registry_init_${DEPLOY_VERSION}
    file: ./config/init.sh
