REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:/6b9GHpkrgyOCL7T9R1rN7UGEfNA0zJhTj8srnNRa5xL4hTaDlE9ywfVfaPfTOcjSFaejZGc+gT+HByg3tb/mg==,iv:ePbsFjU5CorQ9z10j3t2Eb7yBvE3pLJ88GG8gNUDvKk=,tag:DyRugS4qgiEebiQSl5hgOw==,type:str]
REGISTRY_HTPASSWD: ENC[AES256_GCM,data:goStw6PfzUcxAh3smiZ0RsHlCncyXw1+TQqHNHQELp1xOd9k1wDRESm2vIIrDi7ncnw6R/m2eKYUPUf8pOHdZf+YFULyU9mv6DctbTA7ZWC8,iv:nUO9n+nmS1maHl1RdA1jgJ9XJZnMWV0aIqGm3OS20CU=,tag:yAn51FqWKDwu6yZ4oZs/wg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVENhYzk2UUZYSTBCMmdW
        NjVTLzJwQ1JYcHJpbHBBNFBHUVIyN1JpeEM4CnJHWjAxNVRMZzQvQlJBY1ZsSW1M
        MkQ0WXNpNTdzTUhYRWhKWS9vVXhvcHMKLS0tIDFwT3dTRDBpVkRNYWhrYkpiMllO
        N1BNOUt1bnhYZE95SG0vUktWNmFweU0KRizw28p41u0/CEgDoN1SA9u0bhzSBqrM
        AuMRbaoBoYVhT3g5jftrCLArjoAmnDlUNQ/JZVFSnPnKOaw8GJyHMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-05T07:51:40Z"
  mac: ENC[AES256_GCM,data:pX/CdK2dp4eatcAtZOt+vHtkKyyAgr5YegALl1VTGPf+56br3BSr7vX9N+zCV1mc0WVgw9VIq7xDT4t/HtsnDPKdH/X5oDk3fJfCdNJE8QpIod0ffUt++C+9qErQFMzeObcXfrQUWDCz+RATQ6ktGmty3udyTlGLGZXJsJvpDlw=,iv:m8LRFZHgjT2YiVhLb2T8YJyE9A8SnBJNXevbNwzBO0I=,tag:x1Up028Zb7VZcGw++dMIZA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
