REGISTRY_HTPASSWD: ENC[AES256_GCM,data:DXC54hlMl5D971nua8r/gMMXBpV2lPzjTy756J0IyaEzt4D2yYaIdopyd7ngrzhPxlu7E2dt3Vg7V5h2oZmKanDsYWHqMg7LTxWejYwH3l4f,iv:qfRSrOR3targKkiIJ6gJn2K0LaV9PXj3+ysn/L40pPo=,tag:clyAd5wJna7qo7pfnO9IbA==,type:str]
REGISTRY_HTTP_SECRET_KEY: ENC[AES256_GCM,data:qgqQRfDiYWW8W4D+3qJU4boiAGt16u2oOoAYCvevlxZEOO2I21zSvSikQ5BQgWDbHIVhZ+tgqBIBF6UINO2QZA==,iv:BXW1Z9cSXceVS6+OvSlzLy0OLk9Ej5MXp6YUUmGqVxE=,tag:nfHQNxI5eHCTIIWMVm/zVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRTkzR1pvMkFHVWpMTjJD
        R1ZWUVJKVzBzM2IveGNCRTZIMnAyZGRsKzI0CnJHVk1PY1UyRWZqMmxrWXdJMnZE
        WExqZGhxNVlwNm1GTTVyb2JHV0NWS2sKLS0tIHhSb1QzNU9pMnVuRU96bGhpRXZP
        M1hyN2svaER4U3hrMmMrYjZNQVd5T0EK1JT4L9SfDDNqBEW7zFQGfjzIOX/Fz0li
        sIToB/uQwq7uC1V3owXiIg9ia0o5GBZVrJNCnTGC7bXGEOcrXRd9ZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T19:18:04Z"
  mac: ENC[AES256_GCM,data:nDxyIaV9nZGYX+51M0oBfO2vmeKjRyhlPqEVgyGJ5eM/WBa9k856c30rfd/8UI6GbC60sBrJ0uIUslubfyLzqRou65hr2yYw/t+7rShnnGWsn1tmfpL4HRlDoI+nC4rMxGQbZbRYEx0nyMtJt9eW+TV0yANsPfMpkn0U//RyRY4=,iv:ofLPLXlpNPMKKX0cCNgV1PnmDWBcqopBwkvJCp+ah8k=,tag:0FVvV+FlCfoDqccXxiVMpw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
