# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

include:
  - include.yml

services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:2
    entrypoint: ["/bin/sh", "/etc/borgmatic.d/init.sh"]
    logging:
      <<: *logging
    stop_grace_period: 60s
    environment:
      - TZ=${GLOBAL_TZ}
    secrets:
      - backup_borg_passphrase
      - backup_central_db_password
      - backup_immich_db_password
      - backup_dawarich_db_password
    configs:
      - source: backup_borgmatic_config_common
        target: /etc/borgmatic.d/shared/common.yaml
      - source: backup_borgmatic_config_pg_central
        target: /etc/borgmatic.d/pg-central.yaml
      - source: backup_borgmatic_config_pg_immich
        target: /etc/borgmatic.d/pg-immich.yaml
      - source: backup_borgmatic_config_pg_dawarich
        target: /etc/borgmatic.d/pg-dawarich.yaml
      - source: backup_borgmatic_crontab
        target: /etc/borgmatic.d/crontab.txt
      - source: backup_borgmatic_init
        target: /etc/borgmatic.d/init.sh
      - source: backup_borgmatic_exporter
        target: /etc/borgmatic.d/exporter.py
    volumes:
      - borgmatic-repo:/mnt/borg-repository
      - borgmatic-state:/root/.local/state/borgmatic
      - borg-config:/root/.config/borg
      - borg-cache:/root/.cache/borg
      - borgmatic-metrics:/shared
    networks:
      - infra_postgres
      - infra_backup
    healthcheck:
      test: ["NONE"]
    deploy:
      <<: [*place-main, *deploy]
      update_config:
        order: stop-first
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-large

  borgmatic-exporter:
    image: busybox:latest
    command: ["httpd", "-f", "-p", "9099", "-h", "/shared"]
    logging:
      <<: *logging
    stop_grace_period: 30s
    volumes:
      - borgmatic-metrics:/shared:ro
    networks:
      - infra_metrics
    healthcheck:
      test: ["NONE"]
    deploy:
      <<: [*place-main, *deploy]
      update_config:
        order: start-first
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-tiny

  init-backup:
    image: postgres:17-alpine
    entrypoint: ["/bin/sh", "/init-backup-entrypoint.sh"]
    logging:
      <<: *logging
    stop_grace_period: 30s
    environment:
      - GLOBAL_DB_PROVISIONER_USER=${GLOBAL_DB_PROVISIONER_USER}
    secrets:
      - backup_central_db_password
      - global_db_provisioner_password
    configs:
      - source: backup_init_backup
        target: /init-backup-entrypoint.sh
    networks:
      - infra_postgres
    healthcheck:
      test: ["NONE"]
    deploy:
      <<: [*place-main, *deploy-init]
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-tiny

volumes:
  borgmatic-repo:
  borgmatic-state:
  borg-config:
  borg-cache:
  borgmatic-metrics:

networks:
  infra_postgres:
    external: true
  infra_backup:
    external: true
  infra_metrics:
    external: true
