secrets:
  global_db_provisioner_password:
    name: global_db_provisioner_password_${DEPLOY_VERSION}
    external: true
  backup_borg_passphrase:
    name: backup_borg_passphrase_${DEPLOY_VERSION}
    external: true
  backup_central_db_password:
    name: backup_central_db_password_${DEPLOY_VERSION}
    external: true
  backup_immich_db_password:
    name: backup_immich_db_password_${DEPLOY_VERSION}
    external: true
  backup_dawarich_db_password:
    name: backup_dawarich_db_password_${DEPLOY_VERSION}
    external: true

configs:
  backup_borgmatic_config_common:
    name: backup_borgmatic_config_common_${DEPLOY_VERSION}
    file: ./config/borgmatic/common.yaml
  backup_borgmatic_config_pg_central:
    name: backup_borgmatic_config_pg_central_${DEPLOY_VERSION}
    file: ./config/borgmatic/pg-central.yaml
  backup_borgmatic_config_pg_immich:
    name: backup_borgmatic_config_pg_immich_${DEPLOY_VERSION}
    file: ./config/borgmatic/pg-immich.yaml
  backup_borgmatic_config_pg_dawarich:
    name: backup_borgmatic_config_pg_dawarich_${DEPLOY_VERSION}
    file: ./config/borgmatic/pg-dawarich.yaml
  backup_borgmatic_crontab:
    name: backup_borgmatic_crontab_${DEPLOY_VERSION}
    file: ./config/borgmatic/crontab.txt
  backup_borgmatic_init:
    name: backup_borgmatic_init_${DEPLOY_VERSION}
    file: ./config/borgmatic/init.sh
  backup_borgmatic_exporter:
    name: backup_borgmatic_exporter_${DEPLOY_VERSION}
    file: ./config/borgmatic/exporter.py
  backup_init_backup:
    name: backup_init_backup_${DEPLOY_VERSION}
    file: ./config/bootstrap/init-backup.sh
