BACKUP_BORG_PASSPHRASE: ENC[AES256_GCM,data:NsXLmFHsWOe8UeSyIivKdwDJF9s0bf47/VA/gEJBvV5/SgJktvL2VyuNSNTGslX/xvu/ps4J8Xr4itFzxn3EtA==,iv:Bqf8wHOff2GYBHMfZXIWxeLmrthPuB5Q00Sa2QUjkx4=,tag:FWiKKLe3K1y/640IeWoOIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWCtrbjc5cFoza0NRVmZk
        bkVqRXVRTTlEZHVJZGZ3SFBuUVdIaG1TaGdFCm4zU2VuU1YyM1djelJmb3k5enpo
        cWpQNmRMd3VyM1VSdWswK1FSaHBzOEEKLS0tIEtDT21RQnBxVDZ2U1VKamlKZXlU
        VHA0NUwwL3hFd1ZNT3NPR1FTdUZKd2sKGudHCD+19dXsQOj11bTzPAS7G+oOUfUS
        BJG9OoSDpMNw5RwJjNAdRJVd+KOijw1RNANkrRASzD8dBMjjodC5fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T19:18:04Z"
  mac: ENC[AES256_GCM,data:eNlzEN/sx47FkiifJQvCabZqe2PFSMItBdLuPaA4rAkfVarArvWyOgaTjwbWF84QqSt+6XxOsndI33C8+rm0WUAowi1/nWkV1JDKrQs8qUokzYQrLq+OIRqm/5mL5UKrJqVUGpknV8ZXUcObq/74VAjeww+bkisH0bUyP2/IbOE=,iv:ZQ1tPNmxtCrltpj1nWcTHJq3KWm/LMKFkrqiUd5J1OM=,tag:kBMagm+s7RwFt3pz/ZiXgA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
