BORG_PASSPHRASE: ENC[AES256_GCM,data:mmJM/DA21FJtc2vSa93OjsnJZm+NqbbLLYH3/QMI7hHMcO0dBRN0CjDe50JRUIMAMV7tUzVrI7/5+bZqxKhMyQ==,iv:tNJhK+OgLFBLcvRe5uTvDdqbQajG+EBr23yA/+Sa5yU=,tag:vGdYCqXGl38y21e1Q5EARA==,type:str]
POSTGRES_BACKUP_DB_PASSWORD: ENC[AES256_GCM,data:ku5xxypaq+VgltGFKWzB3s7/WfwA7Esd91PntScP/TuMbRq+BmoxPv4ZuOqahtfMH6BWbPi9XwsgIZY3ZaWkag==,iv:SGvVnvW4g1mDVS/LZ6QY0+2GArTk+ds462eTgAy/YUc=,tag:RRUnp8jNNFb18j2gWUsDtQ==,type:str]
IMMICH_BACKUP_DB_PASSWORD: ENC[AES256_GCM,data:NncHBHfIZ/Sxv1eooh9QY668Y4ZWKEIztakYl9Pt1/bn2yqjxkgJgEtqzPp8zhT47kGoEC3YTMpFErxou5sg2A==,iv:giWywkS2Wcw+TzK/DsbETbLgK0oy9zJ+Juq+0SNHoZc=,tag:oxt+UX7nYhO0Eg7JnwjxXw==,type:str]
DAWARICH_BACKUP_DB_PASSWORD: ENC[AES256_GCM,data:pJLMt7nRqbWk8ZVK683oF/JgLUVCqKw8obgY9ZrLDDLcs6sX3nMWXbDp4ln+TjIk3ZPYxRza4DsmObOXhgi3pQ==,iv:gaKAi1nsIqxdYWed8Fl17/SxsDVcKFCvoxMFMGQx/6U=,tag:L5iUqVCCdpG7EzMiBUsWRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT0RoWjF4RFpFTmR4WXR1
        cDF0ZW9UMjh0QkI1U1FZdlk2YjhJMmVLRjMwCnVlQ1FxL3N3LzA4UkVhQ3c0dzRS
        aExVYWFydG9WVWk0azdld24zcm1sczgKLS0tIEZMUUQ5RXpCVFNjOE9VUnlDaHc0
        eXJyeHJtRUdUSjR1emRBSCtuUVJUdnMKrW77I9lrzN3+K2HhuaKuOqjN+hG5a3hZ
        Ea73NyPW1ja8oP5A2bLItSiwVsRXfnVthM0FzLQx9STMpBBw+lZMYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-05T07:50:41Z"
  mac: ENC[AES256_GCM,data:UqRBiY3yv86OifAcLr9LUa3+oqHe1UBLN2r+51M5bdVZXhdPriuYIbBLuqWXWhbVSML2EJKAXssNU7kA17qv79NT52M25L3pejgOeZm/KaOj/khFgRSbIWyCSH7/P9nzrHTYkUgmPm0WHaMcO8Rc5ludJGG/iGZ1g/Lavzb2oDg=,iv:bxhRZ8NTTbELXmaUhFCDYWFFuLvTuAMvUgrQlQEJEUw=,tag:OneIs0ev/FN70OP2g5C4Pw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
