configs:
  prometheus_config:
    name: prometheus_config_${DEPLOY_VERSION}
    file: ./config/prometheus/prometheus.yml
  prometheus_rules:
    name: prometheus_rules_${DEPLOY_VERSION}
    file: ./config/prometheus/node_rules.yml
  grafana_ini:
    name: grafana_ini_${DEPLOY_VERSION}
    file: ./config/grafana/grafana.ini
  grafana_datasource:
    name: grafana_datasource_${DEPLOY_VERSION}
    file: ./config/grafana/datasource.yml
  grafana_dashboards_provisioner:
    name: grafana_dashboards_provisioner_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards.yml
  grafana_dashboard_crowdsec_prom:
    name: grafana_dashboard_crowdsec_prom_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/crowdsec-prom.json
  grafana_dashboard_crowdsec_loki:
    name: grafana_dashboard_crowdsec_loki_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/crowdsec-loki.json
  grafana_dashboard_traefik:
    name: grafana_dashboard_traefik_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/traefik-standalone.json
  grafana_dashboard_syncthing:
    name: grafana_dashboard_syncthing_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/syncthing-metrics.json
  grafana_dashboard_borgmatic:
    name: grafana_dashboard_borgmatic_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/borgamatic-logs.json
  grafana_dashboard_uptimekuma:
    name: grafana_dashboard_uptimekuma_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/uptime-kuma.json
  grafana_dashboard_registry:
    name: grafana_dashboard_registry_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/docker-registry.json
  grafana_dashboard_node_exporter:
    name: grafana_dashboard_node_exporter_${DEPLOY_VERSION}
    file: ./config/grafana/dashboards/node-exporter.json
  init_db_entrypoint:
    name: metrics_init_db_${DEPLOY_VERSION}
    file: ./config/bootstrap/init-db.sh
