METRICS_GRAFANA_DB_PASSWORD: ENC[AES256_GCM,data:LtPV8kkrjxmG3+EwjXu+sG6o51kz37l9LDpnlOtnCckGFL5vy69Ny1lGcoEBpFD2vJKNXzbwHuTbisEp9BkQAg==,iv:vyiaUvnMKiCLTNAyRWlQCfSQyj/zZzp9jjtdykmjtM0=,tag:mijtXyEnDkBqGJCyNNHx8w==,type:str]
METRICS_GRAFANA_SECRET_KEY: ENC[AES256_GCM,data:yYAhptQwHJR3fy+GSsofrW3/2lpu7XHZKvmrFsvcgYxo+naiR2zrQSHcT+5DlGF3Msy+8YeHVhcH+ITSDmNBZQ==,iv:Q7CcoU9jeoFAgW6y1aC8U+OgcEp9xguwz56vLRwhqGo=,tag:wFrEU18c3sORCvCTv+f8Qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T09vS3dWcjFubUJXS1d4
        bFJsWTRMb0RtMjVJL1k1R1BQOUQrd1ZHbzFZCkpOOUM1OWJVT1haQWpaUENnR3JR
        YmNGc0UxZnNHREt3bVBTcDJFM09mRlUKLS0tIFZXSDlIZGcxSTdudSsrQnl2R0J5
        QTZqbDd4Q3VWRjRVc1dRZlNRWVFPSzQKGJGeDCPOl+0wF1TiN2ygCb2suirfkn/O
        hezZ5uYj2XTV3Q433j8ZXtKgh1pRqFYYCqOqUD9G5quJM6Aqqgyn/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T19:18:04Z"
  mac: ENC[AES256_GCM,data:FKM+U2I4bG+fEXeBSDMeHhc3ZNtq2Zg+JY42CUg02u7N15/i5sAOAEwy8IX4YF3vqTgxP3N2k8uX3wkFyHVGdRdO3Ut/y1ufbpySViEWkWBkuZqkSDFB1jgNYU38QrlaLZMAaaN1CZ7T/gm/9dhRwRTw1q60AuWEPX2x+Ay01wA=,iv:4+JfuZ4tSLqhJWq3E14nPgRWYY5Kj1YbxpUW466RlVU=,tag:3aDnul05l69zm9Y9pNukig==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
