GRAFANA_OIDC_CLIENT: ENC[AES256_GCM,data:3ktexYNh4g==,iv:ZKQe7OVWPtNXe4SbUCySXMcoIkA3iN9ugP66yUu0CIY=,tag:jymxmyh1OYz2ekRpCIxi+w==,type:str]
GRAFANA_OIDC_SECRET: ENC[AES256_GCM,data:e7vl9Oy4JdIXYirQGPsPdKIFCM7hbbVJiHIMCSjZJsPN7nEeYpeu5l5aoilEhOT3b0f5C3ZyaXuRxnoK4ppQqGfQ0HSfAAAp,iv:cekxhgIpU5bTHETiyCDqTPvlGNGaHMxu93/N2t8YYzc=,tag:1wuMgaBy7ONh7dvCmMVzjA==,type:str]
GRAFANA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:/GyLtSWOGVOfRXmbbui+N3p+o2LH4G1jj9SfPr0XOz7bf9vJuuy8NvFBtEnFJI5ebdMVE/EMmRR87F31SG+41Q==,iv:xYKatZNglV3z/E/Vj94Qt6VzeQTOHcT2XHRHnqoHHHE=,tag:+T+1kk7d6Hcmub9hLRpW4w==,type:str]
GRAFANA_SECRET_KEY: ENC[AES256_GCM,data:pbnKPuiGVrq5SZnVaH9fmoKvXqo+Nax3Tr2gu4De5M9585TDi4+sYGO9NYPCkfnNpLVRrZZnj+Zo+i+2DKHzEw==,iv:rwQe8gsG7LzWy8J00FJuIXqvch+imUyuhIh8rCFepzE=,tag:NrnXoA/CN+j2+wGhw8KTTQ==,type:str]
SYNCTHING_API_KEY: ENC[AES256_GCM,data:8ZXJ2PbpgKkzE/8HA2JC/LkuFiYPR0N/g3fPCQR/H6w=,iv:bOWYhPYB4LEwhrmebqUioat/ru31nzkxe9aIW9xF954=,tag:SHAfJVlUw4aQQH/yZR/PwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMlp1TFl6Sm12NlZnVDFV
        RlZMOHI2dTBSak8rWDN2VUZPSnF3enp4OXlFCkhlMTZmSmNFWU9tMzJ2TTJkRUh0
        MmVhVXZxYWpUS3RzTVRGMFBYckN6ckkKLS0tIGRkUFJtUmFTYkkzb0V2WDRDRG9O
        M2RIQVhUeUN0Z0hnZkRybmM5WXkydFUKJfOoTE7xrIrzHJjQWVkIpSyy4KSn9Tqb
        YZv9npCz3jp5bIL9psPfMH0rbaQG4hGHNg1HdRUVW5WPJRVS9PhUjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-05T07:50:42Z"
  mac: ENC[AES256_GCM,data:LtAZDed1KlKoM62H/5+9GkLeoTjN7/pLmPjvp0/sLue+4nEwlYXQXcS2nzAvClpcqgd1WT8YitSCN8mfnUpEhfWobqwEZHxNGUjhBuXDNJbWfNUu1FSZ0Mzn/FR3qqV/UTeyp6Un2UJAkqkGBlIVw+hAjdsmoFsnAyhMrNZiRGY=,iv:81KKwQnOU3ednaTTigI3S1U3JwKwCgLWTPghSY/fyww=,tag:iQ4KQoyDyNxESdrQeo9fkA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
