secrets:
  grafana_oidc_client:
    name: grafana_oidc_client_${DEPLOY_VERSION}
    external: true
  grafana_oidc_secret:
    name: grafana_oidc_secret_${DEPLOY_VERSION}
    external: true
  grafana_postgres_password:
    name: grafana_postgres_password_${DEPLOY_VERSION}
    external: true
  grafana_secret_key:
    name: grafana_secret_key_${DEPLOY_VERSION}
    external: true
  syncthing_api_key:
    name: syncthing_api_key_${DEPLOY_VERSION}
    external: true
  uptime_kuma_api_key:
    name: uptime_kuma_api_key_${DEPLOY_VERSION}
    external: true
