---
## https://github.com/gethomepage/homepage/blob/dev/docs/configs/bookmarks.md

- Bookmarks:
    - Comet:
        - icon: glinet-dark
          abbr: GL
          description: " "
          href: https://comet.home.arpa
    - Ruckus:
        - icon: https://www.ruckusnetworks.com/favicon.ico
          abbr: RU
          description: " "
          href: https://ruckus.home.arpa
    - Binardat:
        - icon: mdi-switch
          abbr: BN
          description: " "
          href: http://binardat.home.arpa
    - PiGM:
        - icon: home-assistant-alt
          abbr: PI
          description: " "
          href: http://pigm:8123
    - Tailscale:
        - icon: tailscale-light
          abbr: TS
          description: " "
          href: https://login.tailscale.com/admin/machines
    - Cloudflare:
        - icon: cloudflare
          abbr: CF
          description: " "
          href: https://dash.cloudflare.com
    - RackNerd:
        - icon: racknerd-dark
          abbr: RN
          description: " "
          href: https://nerdvm.racknerd.com/login.php
