---
- Infrastructure:
    - Home Assistant:
        href: https://home.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
        icon: home-assistant.svg
        description: Smart Home Automation
        widget:
          type: homeassistant
          url: http://hass.home.arpa:8123
          key: {{HOMEPAGE_VAR_HASS_KEY}}
          custom:
            - state: zone.home
              label: People Home
            - template: "{{ states.light|selectattr('state','equalto','on')|list|length }} / {{ states.light|list|length }}"
              label: Lights On
            - state: vacuum.roomba
              label: Roomba
    - Proxmox:
        href: https://proxmox.{{HOMEPAGE_VAR_DOMAIN_PUBLIC}}:8006
        icon: proxmox-light.svg
        description: Proxmox Virtual Environment
        widget:
          type: proxmox
          url: https://proxmox.{{HOMEPAGE_VAR_DOMAIN_PUBLIC}}:8006
          username: {{HOMEPAGE_VAR_PVE_USER}}
          password: {{HOMEPAGE_VAR_PVE_PASS}}
          fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - OpenWRT:
        href: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
        icon: openwrt.svg
        description: "GL-MT6000 Router"
        widget:
          type: openwrt
          url: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
          username: root
          password: {{HOMEPAGE_VAR_MAIN_PASS}}
          # interfaceName: eth1
    - AdGuard Home:
        href: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}/adguard/#logs
        icon: adguard-home.svg
        description: Flint
        widget:
          type: adguard
          url: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}/adguard
          username: {{HOMEPAGE_VAR_MAIN_USER}}
          password: {{HOMEPAGE_VAR_MAIN_PASS}}
          fields: ["queries", "blocked", "latency"]
