---
- External:
    - Proxmox NUC:
        href: https://nuc.lan.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}:8006
        icon: proxmox-light.svg
        widget:
          type: proxmox
          url: https://nuc.lan.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}:8006
          username: {{HOMEPAGE_VAR_PVE_NUC_USER}}
          password: {{HOMEPAGE_FILE_PVE_NUC_PASSWORD}}
          fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - Proxmox NAS:
        href: https://nas.lan.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}:8006
        icon: proxmox-light.svg
        widget:
          type: proxmox
          url: https://nas.lan.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}:8006
          username: {{HOMEPAGE_VAR_PVE_NAS_USER}}
          password: {{HOMEPAGE_FILE_PVE_NAS_PASSWORD}}
          fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
    - OpenWRT:
        href: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
        icon: openwrt.svg
        widget:
          type: openwrt
          url: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
          username: root
          password: {{HOMEPAGE_FILE_GLOBAL_ADMIN_PASSWORD}}
          # interfaceName: eth1
    - AdGuard Home:
        href: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}/adguard/#logs
        icon: adguard-home.svg
        widget:
          type: adguard
          url: https://luci.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}/adguard
          username: {{HOMEPAGE_VAR_GLOBAL_ADMIN_USER}}
          password: {{HOMEPAGE_FILE_GLOBAL_ADMIN_PASSWORD}}
          fields: ["queries", "blocked", "latency"]

- Applications:
    - Home Assistant:
        href: https://home.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
        icon: home-assistant.svg
        widget:
          type: homeassistant
          url: http://hass.home.arpa:8123
          key: {{HOMEPAGE_FILE_HASS_TOKEN}}
          # fields: ["people_home", "lights_on"]
          custom:
            - state: zone.home
              label: People Home
            - template: "{{ states.light|selectattr('state','equalto','on')|list|length }} / {{ states.light|list|length }}"
              label: Lights On
            - state: vacuum.kitchen_roomba
              label: Roomba
    - Gluetun:
        icon: gluetun.svg
        widget:
          type: gluetun
          version: 2
          url: http://docker-lxc:8000
          fields: ["public_ip", "region", "country"]
          # key: {{HOMEPAGE_VAR_GLUETUN_API_KEY}}

- Media:
    - qBittorrent:
        href: https://torrent.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
        icon: qbittorrent.svg
        widget:
          type: qbittorrent
          enableLeechSize: false
          enableLeechProgress: false
          username: {{HOMEPAGE_VAR_GLOBAL_ADMIN_USER}}
          password: {{HOMEPAGE_FILE_GLOBAL_ADMIN_PASSWORD}}
          fields: ["leech", "seed", "download", "upload"]
          url: https://torrent.{{HOMEPAGE_VAR_DOMAIN_PRIVATE}}
