---
## https://github.com/gethomepage/homepage/blob/dev/docs/configs/settings.md

favicon: https://www.svgrepo.com/show/410412/home.svg
title: Homepage
useEqualHeights: true
headerStyle: boxed
target: _self
hideVersion: true
color: neutral
showStats: false
fullWidth: true
statusStyle: "dot"

layout:
  Bookmarks:
    header: false
    style: row
    columns: 5
    target: _blank
    iconsOnly: false
  Infrastructure:
    header: false
    style: row
    columns: 3
  Applications:
    header: false
    style: row
    columns: 3
  Media:
    header: false
    style: row
    columns: 3
