# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

include:
  - configs.yml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    user: ${GLOBAL_NONROOT_DOCKER}
    logging:
      <<: *logging
    stop_grace_period: 30s
    environment:
      - LOG_TARGETS=stdout
      - HOMEPAGE_ALLOWED_HOSTS=dash.${DOMAIN_PRIVATE}
      - HOMEPAGE_VAR_MAIN_USER=${GLOBAL_USERNAME}
      - HOMEPAGE_VAR_MAIN_PASS=${GLOBAL_PASSWORD}
      - HOMEPAGE_VAR_DOMAIN_PRIVATE=${DOMAIN_PRIVATE}
      - HOMEPAGE_VAR_DOMAIN_PUBLIC=${DOMAIN_PUBLIC}
      - HOMEPAGE_VAR_JELLYFIN_KEY=${HOMEPAGE_VAR_JELLYFIN_KEY}
      - HOMEPAGE_VAR_PORTAINER_KEY=${HOMEPAGE_VAR_PORTAINER_KEY}
      - HOMEPAGE_VAR_MEALIE_KEY=${HOMEPAGE_VAR_MEALIE_KEY}
      - HOMEPAGE_VAR_GRAFANA_USER=${HOMEPAGE_VAR_GRAFANA_USER}
      - HOMEPAGE_VAR_GRAFANA_PASS=${HOMEPAGE_VAR_GRAFANA_PASS}
      - HOMEPAGE_VAR_IMMICH_KEY=${HOMEPAGE_VAR_IMMICH_KEY}
      - HOMEPAGE_VAR_RADARR_KEY=${HOMEPAGE_VAR_RADARR_KEY}
      - HOMEPAGE_VAR_SONARR_KEY=${HOMEPAGE_VAR_SONARR_KEY}
      - HOMEPAGE_VAR_PROWLARR_KEY=${HOMEPAGE_VAR_PROWLARR_KEY}
      - HOMEPAGE_VAR_PVE_USER=${HOMEPAGE_VAR_PVE_USER}
      - HOMEPAGE_VAR_PVE_PASS=${HOMEPAGE_VAR_PVE_PASS}
      - HOMEPAGE_VAR_HASS_KEY=${HOMEPAGE_VAR_HASS_KEY}
      - HOMEPAGE_VAR_AUTHENTIK_KEY=${HOMEPAGE_VAR_AUTHENTIK_KEY}
      - HOMEPAGE_VAR_CROWDSEC_USER=${HOMEPAGE_VAR_CROWDSEC_USER}
      - HOMEPAGE_VAR_CROWDSEC_PASS=${HOMEPAGE_VAR_CROWDSEC_PASS}
    configs:
      - source: homepage_settings
        target: /app/config/settings.yaml
      - source: homepage_bookmarks
        target: /app/config/bookmarks.yaml
      - source: homepage_widgets
        target: /app/config/widgets.yaml
      - source: homepage_docker
        target: /app/config/docker.yaml
      - source: homepage_custom_css
        target: /app/config/custom.css
      - source: homepage_custom_js
        target: /app/config/custom.js
      - source: homepage_services
        target: /app/config/services.yaml
      - source: homepage_kubernetes
        target: /app/config/kubernetes.yaml
      - source: homepage_proxmox
        target: /app/config/proxmox.yaml
    networks:
      - infra_gw-internal
      - infra_socket
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      <<: [*place-vm, *deploy]
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.scope.internal=true"
        - "traefik.http.routers.homepage.rule=Host(`dash.${DOMAIN_PRIVATE}`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      mode: replicated
      replicas: 1
      resources:
        <<: *resources-medium

networks:
  infra_gw-internal:
    external: true
  infra_socket:
    external: true
