ACCOUNTS_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:eAOEaGAMUGKaDCRSwTDFzCFTpZZP1r6qLB9x8vDNzUEjVDzAlwDKCE1CJRWGUNXBJKtzLa/+bFLOQrWJeCxBTg==,iv:o43PM9mlkHXPBrKUBGUuXZp287PcJzGsdiR7pKvoYi4=,tag:kMeJynrK7zEtmNBmDEEDjw==,type:str]
ACCOUNTS_AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:haEZTMTHhqmOXyRMcF/tRGTLfrC4bAdM15g5INcXg9+mzqB3rC7SWpLGTcjpCtvuVT9vMpN4+bUnNCYNMcT/Pw==,iv:Iea9LZdNZ3IpYnCOeWw897uY4kMD/ThnrrP4m6GE+u8=,tag:hhU0DJ7P5jCnTNjrgXh5bQ==,type:str]
ACCOUNTS_AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:6V4FoSXd23fR9IzI3ybkZuKkeCDnzeu2irj4iBe852SJO8dVDnu+HX9alaQcRb5QQXP4xWF1UKI2nlh+y1yjcw==,iv:hi0th9kWtqNmjKP4UxbSwcORLexfBFfe9IGxD7awOBs=,tag:/QJNFQEKCghujaJ7VZ9xjw==,type:str]
ACCOUNTS_LLDAP_KEY_SEED: ENC[AES256_GCM,data:9Pgy7vUfg5DS3DPhW1pf/9heQGpIyYz8AH4EYv9ayHw=,iv:nTqNaWVW+XB8Ja+EPCohXtayUoyaU3i3ZAGPCc//h2E=,tag:bPVIyG2CchL2xytSrKjHOQ==,type:str]
ACCOUNTS_LLDAP_JWT_SECRET_KEY: ENC[AES256_GCM,data:SNfVubVvW5d1vq114BIkPvpBEiQG+v6W861AfV07SWg=,iv:nphNrc1qUaGpCyVVgU2hZa6JgpT/rRrpmdQ7ijAis7E=,tag:VrnQOLjVeh68cN/O6hVztw==,type:str]
ACCOUNTS_LLDAP_DB_PASSWORD: ENC[AES256_GCM,data:22Y8iMBMZFxNRGUaPcvV3nQP/8CHbfQqxWahTdzfIyibm4Uh85JVw8CxH+aUMxThHDxMwgEoubkHi5BuqGV9YA==,iv:VFZR0gyggDArdJVIpIu3Dv+I6epGtCcizMXC8oA8wgY=,tag:fsKOt65RMR9GLFWmWwvruA==,type:str]
ACCOUNTS_LLDAP_DB_URL: ENC[AES256_GCM,data:vLCYvtVKVl8pQ/cp3B6iDcRkXr3KJ5+GE53Duon0rzvUzXU594n6FeALYeertuC0+phTVHghBZiIkoSUnFkMCYWlfgaQE7VIv0T1NvE2Eu3kRHw6dZfj/ycWHHGoubuwcx34rCs=,iv:TKhj5sNT+TR7WpZemDbFQJ9fieXfHh9vii7w7lYMuB4=,tag:ulWk8dLbr89RxPpw38L4Bg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RS9FbS82WjdEdDJzR0s3
        anVRNUhyNzQrbUdJYnA4bUM3ai9QNGx1YXp3ClFDNHdVdThWVVBoOWtpL3NkYko5
        bW5OU1JlbGU5cjZYalhwMFBQQnV5SkEKLS0tIEcxc09IcnRtUUJJcHdMbURyVHRN
        OER5K1hBQTFqM1JsTlc4TjBzTks0NW8K3qSMDOIMTgZS6UCnNrkEWhVB8yGbvkS6
        x0rKFxHbS4lcyyPBqvbklGjbBUQ4904G0Smjy9kNVSlHU4CThDVwRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xcnm9hkeyrrjxz33tvufpxwfwc8ydkwt3dax6kqsklpvggatj5usna7r2l
  lastmodified: "2026-09-07T19:18:04Z"
  mac: ENC[AES256_GCM,data:kx/vWYZ2O31rMOphnB8eEUhGd7DRaTFpnmP8ddwzWMGjfQYYGc4jLD9GYjc6qur/KZYhymQFkE1YuLFbowwAU+EndAt/aAA2zghY6U4wlS91CSYJ2yHNk8r0XXny1YGLmznLWTitwTP+egox8ymOOn+/t0PrE+HV22Q7FcWbwhU=,iv:hDY7U+71NvEzn7+F/1VJ93sDKUThCtHpr5Xc7+2iamE=,tag:2I4ar43nn3f28wpeBo1FGQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
