# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

include:
  - configs.yml

services:
  jellyfin:
    image: ${GLOBAL_SWARM_OCI_REGISTRY}/jellyfin/jellyfin:${OCI_TAG_JELLYFIN}
    entrypoint: ["/bin/sh", "/init.sh"]
    logging:
      <<: *logging
    stop_grace_period: 30s
    environment:
      - JELLYFIN_OWNER=${GLOBAL_NONROOT_DOCKER}
      - RUSTICL_ENABLE=radeonsi
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
    networks:
      - infra_gw-external
      - infra_gw-internal
    # ports:
    #   - target: 8096
    #     published: 8096
    #     protocol: tcp
    #     mode: host
    volumes:
      - /dev/dri:/dev/dri
      - /mnt/media:/media
      - jellyfin-config:/etc/jellyfin
      - jellyfin-data:/var/lib/jellyfin
      - jellyfin-logs:/var/log/jellyfin
      - jellyfin-cache:/var/cache/jellyfin
    configs:
      - source: jellyfin_init
        target: /init.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      <<: [*place-gpu, *deploy]
      update_config:
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - "traefik.scope.external=true"
        - "traefik.http.routers.jellyfin-external.rule=Host(`stream.${DOMAIN_PUBLIC}`)"
        - "traefik.http.routers.jellyfin-external.entrypoints=websecure"
        - "traefik.http.routers.jellyfin-external.service=jellyfin"
        - "traefik.scope.internal=true"
        - "traefik.http.routers.jellyfin-internal.rule=Host(`stream.${DOMAIN_PRIVATE}`)"
        - "traefik.http.routers.jellyfin-internal.entrypoints=websecure"
        - "traefik.http.routers.jellyfin-internal.service=jellyfin"
        - "homepage.group=Applications"
        - "homepage.name=Jellyfin"
        - "homepage.icon=jellyfin"
        - "homepage.href=https://stream.${DOMAIN_PRIVATE}"
        - "homepage.description=Movies & TV"
        - "homepage.widget.type=jellyfin"
        - "homepage.widget.url=https://stream.${DOMAIN_PRIVATE}"
        - "homepage.widget.key={{HOMEPAGE_VAR_JELLYFIN_KEY}}"
        - "homepage.widget.enableNowPlaying=false"
        - "homepage.widget.enableBlocks=true"
        - 'homepage.widget.fields=["movies", "series", "episodes"]'
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M
          generic_resources:
            - discrete_resource_spec:
                kind: "gpu"
                value: 1

volumes:
  jellyfin-config:
  jellyfin-data:
  jellyfin-logs:
  jellyfin-cache:

networks:
  infra_gw-external:
    external: true
  infra_gw-internal:
    external: true
